SALON:
  Giris:
    x: -0.7384400599893532
    y: 1.1176209288360368
    z: -0.0498330199734705
    w: 0.998757563235605
  Temizlik:
    - {x: -1.0966168642044067, y: 3.5416643619537354, z: 0.0, w: 1.0}
    - {x: -3.7649736404418945, y: 1.073171854019165, z: 0.0, w: 1.0}
    - {x: -0.8032229542732239, y: 1.2328864336013794, z: 0.0, w: 1.0}

MUTFAK:
  Giris:
    x: -4.145525381580453
    y: 1.7769802403333055
    z: 0.9999790948150499
    w: 0.006466060073457085
  Temizlik:
    - {x: -6.655375003814697, y: 2.2351694107055664, z: 0.0, w: 1.0}
    - {x: -5.850343704223633, y: 2.8236496448516846, z: 0.0, w: 1.0}
    - {x: -5.688170433044434, y: 4.62660551071167, z: 0.0, w: 1.0}

KORIDOR:
  Giris:
    x: 0.41669725743072716
    y: 0.27383626175020215
    z: 0.7262110222650667
    w: 0.6874718547989632
  Temizlik:
    - {x: 0.6796004772186279, y: 0.11687768995761871, z: 0.0, w: 1.0}
    - {x: 1.1562927961349487, y: 0.5019264817237854, z: 0.0, w: 1.0}
    - {x: 2.0399017333984375, y: 0.240562811493873, z: 0.0, w: 1.0}

YATAKODASI:
  Giris:
    x: 2.906681515875883
    y: 0.6435640469695788
    z: -0.7689501871557356
    w: 0.6393086966975807
  Temizlik:
    - {x: 6.252098083496094, y: 1.0236765146255493, z: 0.0, w: 1.0}
    - {x: 6.493058204650879, y: 3.9582583904266357, z: 0.0, w: 1.0}
    - {x: 3.0199759006500244, y: 2.8727474212646484, z: 0.0, w: 1.0}
